import { test, expect } from '@playwright/test'

test('start screen hides the board until Start, then shows a prompt and fresh round', async ({ page }) => {
  await page.addInitScript(() => { Math.random = () => .999 })
  await page.goto('/')
  await expect(page.locator('#game')).toBeHidden()
  await expect(page.locator('#begin')).toBeEnabled({ timeout: 60000 })
  await page.screenshot({ path: '../docs/start-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../docs/start-mobile.png', fullPage: true })
  await page.clock.install()
  await page.clock.fastForward(31000)
  await expect(page.locator('#result')).toBeHidden()
  await page.locator('#begin').click()
  await expect(page.locator('#welcome')).toBeHidden()
  await expect(page.locator('#canvas')).toBeVisible()
  await expect(page.locator('#prompt')).toHaveText('Draw an airplane')
  await expect(page.locator('#prompt')).toBeFocused()
  await expect(page.locator('#seconds')).toHaveText('30')
  await expect(page.locator('.drawing-instructions')).toBeVisible()
  await page.screenshot({ path: '../docs/round-mobile.png', fullPage: true })
  await page.clock.fastForward(31000)
  await expect(page.locator('#result')).toContainText("Time's up!")
  await page.locator('#home').click()
  await expect(page.locator('#game')).toBeHidden()
  await expect(page.locator('#begin')).toBeFocused()
  await page.locator('#begin').press('Enter')
  await expect(page.locator('#seconds')).toHaveText('30')
  await expect(page.locator('#result')).toBeHidden()
  await expect(page.locator('#clear')).toBeDisabled()
})

test('practice has no timer and returning home stops the camera', async ({ page }) => {
  await page.goto('/')
  await page.locator('#practice').click()
  await expect(page.locator('#prompt')).toHaveText('Draw anything you like')
  await expect(page.locator('.timer')).toBeHidden()
  await page.locator('#camera').click()
  await expect(page.locator('#camera')).toHaveText('Disable camera', { timeout: 60000 })
  await page.evaluate(() => {
    (window as any).savedTracks = ((document.querySelector('video') as HTMLVideoElement).srcObject as MediaStream).getTracks()
  })
  await page.locator('#home').click()
  expect(await page.evaluate(() => (window as any).savedTracks.every((t: MediaStreamTrack) => t.readyState === 'ended'))).toBe(true)
  await expect(page.locator('#game')).toBeHidden()
})
